---
# Hopefully chezmoi gets in a repo/ppa soon
- name: Get latest chezmoi release
  uri:
    url: https://api.github.com/repos/twpayne/chezmoi/releases/latest
    return_content:
    body_format: json
  changed_when: False
  register: chezmoi_release

- name: Extract current release download url
  set_fact:
    chezmoi_download_url: "{{ chezmoi_release.json | json_query('assets[].browser_download_url') | select('search', '_linux_amd64.deb') | first }}"

- name: Install or update chezmoi package
  apt:
    deb: "{{ chezmoi_download_url }}"