---
- name: Add deadsnakes ppa
  apt_repository:
    repo: ppa:deadsnakes/ppa

- name: Install python3.7
  apt: pkg=python3.7 state=latest

- name: Make python3.7 virtualenv
  become: yes
  become_user: '{{ user }}'
  shell: virtualenv {{ lookup('env', 'HOME') }}/.pywork -p python3.7
  args:
    creates: "{{ lookup('env', 'HOME') }}/.pywork/"

- name: Check if pywork is in user path
  become: yes
  become_user: '{{ user }}'
  shell: "echo $PATH | grep -q '/.pywork/bin/'"
  register: in_path
  changed_when: no
  failed_when: no

- name: Get user shell
  check_mode: yes
  user:
    user: "{{ user }}"
  register: var_user

- name: Add pywork to user path (fish)
  become: yes
  become_user: '{{ user }}'
  shell: set --prepend -U fish_user_paths "{{ lookup('env', 'HOME') }}/.pywork/bin/"
  when: (in_path.rc == 1) and ("fish" in var_user.shell)
  args:
    executable: /usr/bin/fish

- name: Install pip packages
  become: yes
  become_user: '{{ user }}'
  pip:
    virtualenv: "{{ lookup('env', 'HOME') }}/.pywork/"
    name: "{{ item }}"
  with_items:
    - "{{ pip_packages }}"